# Closing Reports For mangement

In [7]:
import pandas as pd
import datetime
import time
# pd.options.display.float_format = '{:,.2f}'.format

""" Finding the Last Month """

now = datetime.datetime.now()
last_month = now.month
if now.month == 1:
    last_year=now.year-1
else:
    last_year=now.year

last="January February March April May June July August September Octobor November December".split()[last_month-1]
name = "Employee Target vs Achievement "+last+" " +str(last_year)+".xlsx"

# Read the excel sheet to pandas dataframe
df = pd.read_excel("one.xls", sheet_name=0,converters={"DIVISION":str,})
df.head(5)

,CLIENT,START_DATE,END_DATE,TERRITORY_CODE,EMPP_CODE,EMPP_NAME,DESIGNATION,HIERARCHY_LVL,DIVISION,NO_OF_INVOICES,...,NET_VALUE,GROSS_VALUE,PREVMONTH_CREDIT,CURRMONTH_CREDIT,PREVMONTH_DUE_COLLECTION,CURRMONTH_DUE_COL,TOTAL_DUE,CURR_MON_TOTAL_COL,TARGET_AMOUNT,TARGET_ACHV
0,300,01.03.2022,31.03.2022,AGM02-P,EM00000168,Mr. Bishawjit Kumar Shome,"AGM, Sales",9,01,166433,...,450933292,529399604,49723302.17,1.254355e+08,NaN,NaN,1.751588e+08,NaN,544607941,82.799
1,300,01.03.2022,31.03.2022,AGM01-P,EM00001086,Md. Shahjahan,"AGM, Sales",9,01,180052,...,425068554,498882578,36090994.07,1.113474e+08,NaN,NaN,1.474384e+08,NaN,555392059,76.534
2,300,01.03.2022,31.03.2022,NSM03-P,EM00000351,Md. Sultan Mahamud Alam,NSM,8,01,63224,...,168368821,197557249,23617943.30,4.667761e+07,NaN,NaN,7.029555e+07,NaN,213160470,78.986
3,300,01.03.2022,31.03.2022,DSM12-P,EM00000184,Mr. Salim Mahamod,DSM,6,01,40259,...,72272755,85028611,8146782.29,1.396438e+07,NaN,NaN,2.211116e+07,NaN,79571118,90.827
4,300,01.03.2022,31.03.2022,DSM10-P,EM00000359,Md. Wazed Ali,DSM,6,01,24261,...,60239131,70664117,5559562.79,1.607718e+07,NaN,NaN,2.163674e+07,NaN,76429412,78.816

# Hasib vai Employee Target vs Achievement

In [8]:
# Hasib vai Employee Target vs Achievement

hasib = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","HIERARCHY_LVL","DIVISION","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]
hasib.head(2)

writer = pd.ExcelWriter(str(name), engine='xlsxwriter') 
hasib.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

# Raw Master Data

In [9]:
df2 = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","DIVISION","HIERARCHY_LVL","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]

df2['TARGET_AMOUNT'] = df['TARGET_AMOUNT'].div(100000).round(decimals=3)
df2['NET_VALUE'] = df['NET_VALUE'].div(100000).round(decimals=3)
df2["TARGET_ACHV"] = df2["TARGET_ACHV"].round(3)

print("Total ZMIO with vacant Employe : "+ str(df2.shape[0]))

if 'Plant' not in df2.columns:
    df2.insert(2,'Plant',"")

df3 = df2[~df2.EMPP_CODE.str.contains("VAC")]


writer = pd.ExcelWriter("Master_Data.xlsx", engine='xlsxwriter') 
df3.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

print("Total ZMIO Without Employe : "+ str(df3.shape[0]))

df2.head(50)

c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Total ZMIO with vacant Employe : 2757
Total ZMIO Without Employe : 2749

,EMPP_CODE,EMPP_NAME,Plant,TERRITORY_CODE,DIVISION,HIERARCHY_LVL,TARGET_AMOUNT,NET_VALUE,TARGET_ACHV
0,EM00000168,Mr. Bishawjit Kumar Shome,,AGM02-P,01,9,5446.079,4509.333,82.799
1,EM00001086,Md. Shahjahan,,AGM01-P,01,9,5553.921,4250.686,76.534
2,EM00000351,Md. Sultan Mahamud Alam,,NSM03-P,01,8,2131.605,1683.688,78.986
3,EM00000184,Mr. Salim Mahamod,,DSM12-P,01,6,795.711,722.728,90.827
4,EM00000359,Md. Wazed Ali,,DSM10-P,01,6,764.294,602.391,78.816
5,EM00000539,Mr. Chandan Krishna Pandit,,DSM08-P,01,6,392.751,275.827,70.229
6,EM00000572,Md. Rabiul Hossen,,DSM09-P,01,6,1257.691,1018.040,80.945
7,EM00000622,Mr. Khondoker Tariqul Islam,,DSM13-P,01,6,1017.315,766.112,75.307
8,EM00001391,Md. Anwar Hossain,,DSM11-P,01,6,554.564,487.101,87.834
9,EM00002785,Mr. Syed Sakhawat Hossain,,DSM01-P,01,6,1217.248,974.352,80.045
10,EM00010023,Md. Moniruzzaman,,DSM02-P,01,6,1137.595,826.529,72.655
11,EM00011146,Md. Safar Ali,,DSM03-P,01,6,993.300,685.139,68.975
12,EM00000402,Mr. Dipok Kumar Bhowmic,,KERSM1P,01,4,258.819,198.208,76.581
13,EM00000493,Md. Aminul Islam,,ASM10-P,01,4,267.279,200.864,75.151
14,EM00000546,Md. Delower Hossain,,ASM12-P,01,4,258.346,260.296,100.750
15,EM00000679,Mr. Minu Ahmed,,ASM11-P,01,4,405.283,283.920,70.054
16,EM00000693,Md. Masudur Rahman,,ASM17-P,01,4,279.307,214.526,76.806
17,EM00000694,Muhammad Zahidul Islam,,ASM21-P,01,4,256.578,211.507,82.433
18,EM00000773,Muhammad Rakib Hasan,,ASM16-P,01,4,211.591,174.396,82.421
19,EM00000834,Mohammad Rana Mean,,FARSM2P,01,4,225.531,179.296,79.499
20,EM00001027,Mohammad Asraful Islam,,ASM01-P,01,4,184.019,159.103,86.460
21,EM00001054,Md. Hamidur Rahman Sayed,,ASM15-P,01,4,270.302,202.783,75.020
22,EM00001110,Mr. Amal Kanti Das,,CORSM1P,01,4,271.021,201.719,74.429
23,EM00001139,Mr. Anis Howlader,,ASM18-P,01,4,93.994,85.695,91.171
24,EM00001295,Mr. Suman Kumar Sutra Dhar,,ASM19-P,01,4,256.855,225.138,87.651
25,EM00001321,Mohammad Kamal Hossain Mina,,FARSM1P,01,4,242.607,195.290,80.496
26,EM00001395,Md. Khurshid Jahan,,BORSM2P,01,4,192.860,127.837,66.285
27,EM00001485,Md. Humayunur Rashid,,ASM22-P,01,4,450.239,332.440,73.836
28,EM00001495,Md. Mustafizur Rahman,,PARSM4P,01,4,117.525,119.878,102.000
29,EM00001504,Md. Mizanur Rahman,,UTRSM1P,01,4,212.968,178.349,83.744
30,EM00001577,Muhammad Shakhawat Hossain,,ASM13-P,01,4,172.330,150.224,87.172
31,EM00001595,Md. Abdul Baki Bhuyan,,FERSM1P,01,4,305.050,242.758,79.579
32,EM00001758,Mr. Mizanur Rahman,,NORSM2P,01,4,244.909,190.628,77.836
33,EM00001759,Mr. Golam Mostofa,,BBRSM1P,01,4,373.548,273.156,73.124
34,EM00001761,Muhammad Azad Mia,,DHRSM1P,01,4,79.488,81.149,102.080
35,EM00002055,Mohammad Humyun Kabir,,SYRSM1P,01,4,220.884,176.912,80.092
36,EM00002110,Md. Zahid Hossain,,BARSM2P,01,4,220.843,154.871,70.127
37,EM00002176,Mr. Abdur Rahman Khan,,NARSM2P,01,4,261.019,221.511,84.864
38,EM00002252,Muhammad Jakir Hussain,,CURSM2P,01,4,219.928,209.090,95.072
39,EM00002497,Md. Abdullah-Al-Mamun,,NARSM1P,01,4,274.722,238.941,86.975
40,EM00002498,A.K.M. Nazmul Hasan,,CARSM1P,01,4,259.651,246.084,94.774
41,EM00002527,Mohammad Shwokat Ali Khan,,PARSM1P,01,4,81.677,83.102,101.740
42,EM00002548,Md. Abdul Karim,,MYRSM1P,01,4,162.019,114.006,70.365
43,EM00002638,Mr. Shah Kamruzzaman,,PBRSM1P,01,4,188.182,147.927,78.608
44,EM00002806,Mr. S. M. Shofiqul Islam,,KURSM1P,01,4,243.336,175.798,72.244
45,EM00003014,Mohammad Khorshed Alam,,ASM20-P,01,4,241.219,178.432,73.970
46,EM00004112,Mohammad Sadequr Rahman,,KIRSM1P,01,4,270.631,198.158,73.220
47,EM00011153,Md. Tariqul Islam,,BORSM1P,01,4,259.919,169.864,65.352
48,EM00011155,Md. Tanzimul Haque,,DHRSM4P,01,4,105.641,99.959,94.621
49,EM00011172,Rabindra Nath Poddar,,DHRSM2P,01,4,170.644,162.474,95.212

# Shafiq Boss Clossing Raw Data

In [10]:
# Shafiq Boss Data format


# df2 = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","DIVISION","HIERARCHY_LVL","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]

# df2['TARGET_AMOUNT'] = df['TARGET_AMOUNT'].div(100000).round(2)
# df2['NET_VALUE'] = df['TARGET_AMOUNT'].div(100000).round(2)

# print("Total ZMIO Employe : "+ str(df2.shape[0]))


division = ["01","02","04"]
Hieararchy = [2,3,4,5,6,7,8,9,10]

Boss_df = df3[df3.EMPP_CODE != "EM00702459"]

Boss_df2 = Boss_df[Boss_df['DIVISION'].isin(division) & Boss_df['HIERARCHY_LVL'].isin(Hieararchy)]


print("Total Row : " + str(Boss_df.shape[0]))

print("Total Mail count : " + str(Boss_df2.shape[0]))

Boss_df2["TARGET_ACHV"] = Boss_df2["TARGET_ACHV"].round(2)

writer = pd.ExcelWriter("Boss_Raw_Data.xlsx", engine='xlsxwriter') 
Boss_df2.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

Boss_df2.head(150)

Total Row : 2748
Total Mail count : 540

c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,EMPP_CODE,EMPP_NAME,Plant,TERRITORY_CODE,DIVISION,HIERARCHY_LVL,TARGET_AMOUNT,NET_VALUE,TARGET_ACHV
0,EM00000168,Mr. Bishawjit Kumar Shome,,AGM02-P,01,9,5446.079,4509.333,82.80
1,EM00001086,Md. Shahjahan,,AGM01-P,01,9,5553.921,4250.686,76.53
2,EM00000351,Md. Sultan Mahamud Alam,,NSM03-P,01,8,2131.605,1683.688,78.99
3,EM00000184,Mr. Salim Mahamod,,DSM12-P,01,6,795.711,722.728,90.83
4,EM00000359,Md. Wazed Ali,,DSM10-P,01,6,764.294,602.391,78.82
...,...,...,...,...,...,...,...,...,...
145,EM00002603,Mr. Mamun Choudhury,,CH030-P,01,2,36.030,31.823,88.32
146,EM00002613,Mr. Ponir Hossain,,NA020-P,01,2,32.340,33.334,103.07
147,EM00002617,Mr. Monjur Hasan,,PA080-P,01,2,32.260,29.006,89.91
148,EM00002664,Mohammad Shelim Mizi,,SY090-P,01,2,31.240,28.225,90.35
149,EM00002665,Mr. Ratan Sindhu Ray,,SY030-P,01,2,30.630,24.647,80.47

# 100% AND 5 LAC 6 REPORTS

In [11]:
#1-PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT % FOR  AUG 2021

Pmio100ABOVE = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==1) &(df3["TARGET_ACHV"]>=100)]

# P100ABOVE.head(10)
print("PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  " + str(Pmio100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"pharma\PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Pmio100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------


#2-PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT % FOR AUG 2021
Pam100ABOVE = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==2) &(df3["TARGET_ACHV"]>=100)]

# Pam100ABOVE.head(10)
print("PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  " + str(Pam100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"pharma\PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Pam100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()


#----------------------------------------------------------------------------------------------------------


#3-Pharma 5 LAC AND ABOVE SALES MIO-SMIO AUG 2021

Pmio5above = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==1) &(df3["NET_VALUE"]>=5.00)]

# Pmio5above.head(10)
print("Pharma 5 LAC AND ABOVE SALES MIO-SMIO  " + str(Pmio5above.shape[0]))

writer = pd.ExcelWriter(r"pharma\Pharma 5 LAC AND ABOVE SALES MIO-SMIO.xlsx", engine='xlsxwriter') 
Pmio5above.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------



#1-AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT % FOR  AUG 2021

Amio100ABOVE = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==1) &(df3["TARGET_ACHV"]>=100)]

# Amio100ABOVE.head(10)
print("AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  " + str(Amio100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"ag\AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Amio100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------

#2-AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT % FOR AUG 2021

Aam100ABOVE = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==2) &(df3["TARGET_ACHV"]>=100)]

# Aam100ABOVE.head(10)
print("AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  " + str(Aam100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"ag\AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Aam100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()
#----------------------------------------------------------------------------------------------------------


#3-AG 5 LAC AND ABOVE SALES MIO-SMIO AUG 2021

Amio5above = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==1) &(df3["NET_VALUE"]>=5)]

# Amio5above.head(10)
print("AG 5 LAC AND ABOVE SALES MIO-SMIO  " + str(Amio5above.shape[0]))

writer = pd.ExcelWriter(r"ag\AG 5 LAC AND ABOVE SALES MIO-SMIO.xlsx", engine='xlsxwriter') 
Amio5above.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

print("")


print("Total 100 % and above achiver (pharma+ag) : " + str(Pmio100ABOVE.shape[0]+Pam100ABOVE.shape[0]+Amio100ABOVE.shape[0]+Aam100ABOVE.shape[0]))

PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  329
PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  41
Pharma 5 LAC AND ABOVE SALES MIO-SMIO  890
AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  41
AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  1
AG 5 LAC AND ABOVE SALES MIO-SMIO  111

Total 100 % and above achiver (pharma+ag) : 412