##  Exposer

In [86]:
import pandas as pd

In [87]:
df = pd.read_excel("cr_list.xlsx", sheet_name=0)
# df.head()

In [88]:

df['Pharma'] = df.apply(lambda x: x['Pharma Due'] + x['Pharma Transit'], axis=1)
df['AG'] = df.apply(lambda x: x['AG Due'] + x['AG Transit'], axis=1)
df['Onco'] = df.apply(lambda x: x['ONCO Due'] + x['ONCO Transit'], axis=1)
df['Ophtha'] = df.apply(lambda x: x['OPTHA Due'] + x['OPTHA Transit'], axis=1)
# df.head()

In [89]:
data = df[['Customer Number','Pharma','AG','Onco','Ophtha']]
data2=pd.pivot_table(data, values=['Pharma', 'AG', 'Onco', 'Ophtha'], index=['Customer Number'], aggfunc=sum)

data3 = data2.reset_index()




# data3.head(30)
# print(data2.dtypes)


# writer = pd.ExcelWriter("Master_Data.xlsx", engine='xlsxwriter') 
# data2.to_excel(writer, sheet_name='Sheet1',index=True)
# writer.save()





# Pharma.head()

In [90]:
Pharma = pd.DataFrame()
AG = pd.DataFrame()
Onco = pd.DataFrame()
Ophtha = pd.DataFrame()


Pharma['Customer']= data3['Customer Number']
Pharma['Credit']= data3['Pharma']
Pharma['Credit segment'] = '1001'


AG['Customer']= data3['Customer Number']
AG['Credit']= data3['AG']
AG['Credit segment'] = '1002'


Onco['Customer']= data3['Customer Number']
Onco['Credit']= data3['Onco']
Onco['Credit segment'] = '1003'

Ophtha['Customer']= data3['Customer Number']
Ophtha['Credit']= data3['Ophtha']
Ophtha['Credit segment'] = '1004'




Master = pd.DataFrame()

Master = pd.concat([Pharma,AG,Onco,Ophtha], axis=0)

Master['Time Stamp']='2023031230302'
Master['Time Stamp1']='2023031230302'
Master['Credit Exp Cat.']='100'
Master['Empty']=''
Master['Amt']='0.00'
Master['Curr'] = 'BDT'




# Master.head(80)

In [92]:
Master = Master[['Customer','Credit segment','Time Stamp','Time Stamp1','Credit Exp Cat.','Empty','Credit','Amt','Curr']]


writer = pd.ExcelWriter("Credit_Exposer.xlsx", engine='xlsxwriter') 
Master.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

Master.head()

C:\Users\aristo\AppData\Local\Temp\ipykernel_5248\1093251171.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

,Customer,Credit segment,Time Stamp,Time Stamp1,Credit Exp Cat.,Empty,Credit,Amt,Curr
0,4.000022e+09,1001,2023031230302,2023031230302,100,,11510.00,0.00,BDT
1,4.000022e+09,1001,2023031230302,2023031230302,100,,120409.00,0.00,BDT
2,4.000022e+09,1001,2023031230302,2023031230302,100,,47191.01,0.00,BDT
3,4.000022e+09,1001,2023031230302,2023031230302,100,,23019.00,0.00,BDT
4,4.000023e+09,1001,2023031230302,2023031230302,100,,0.00,0.00,BDT